name: Deploy Web App

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - test
          - prod

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir dist
          cp -r index.html js config.template.js dist/

          if [ "${{ github.event.inputs.env }}" = "prod" ]; then
            WEBHOOK="https://nonvillainously-lymphoblastic-susan.ngrok-free.dev/webhook/c7bd9b6b-5edc-4625-b8c0-1c3254d8af4b"
          else
            WEBHOOK="https://nonvillainously-lymphoblastic-susan.ngrok-free.dev/webhook-test/c7bd9b6b-5edc-4625-b8c0-1c3254d8af4b"
          fi

          sed "s|__WEBHOOK__|$WEBHOOK|g" dist/config.template.js > dist/config.js
          rm dist/config.template.js

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4