name: Deploy Web App

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate config.js from template
        run: |
          if [ "${{ github.event.inputs.env }}" = "prod" ]; then
            WEBHOOK="https://nonvillainously-lymphoblastic-susan.ngrok-free.dev/webhook/c7bd9b6b-5edc-4625-b8c0-1c3254d8af4b"
          else
            WEBHOOK="https://nonvillainously-lymphoblastic-susan.ngrok-free.dev/webhook-test/c7bd9b6b-5edc-4625-b8c0-1c3254d8af4b"
          fi

          sed "s|__WEBHOOK__|$WEBHOOK|g" config.template.js > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .